package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// GenerateModuleRegistration 为指定模块生成注册代码
func GenerateModuleRegistration(moduleName, modulePath string) error {
	// 模块注册代码模板
	const tpl = `// Code generated by go-sea module generator. DO NOT EDIT.

package {{.ModuleName}}

import (
	"github.com/gin-gonic/gin"
	"github.com/opentracing/opentracing-go"
	"github.com/yb2020/odoc/internal/database"
	"github.com/yb2020/odoc/pkg/i18n"
	"github.com/yb2020/odoc/pkg/logging"
	"github.com/yb2020/odoc/pkg/registry"
	userservice "github.com/yb2020/odoc/services/user/service"
	"gorm.io/gorm"
)

// 自动注册模块
func init() {
	// 注册需要数据库的处理器
	registry.RegisterWithDB("{{.ModuleName}}", func(r *gin.Engine, db *gorm.DB, logger logging.Logger, tracer opentracing.Tracer) {
		// 创建所需的依赖
		redis := database.GetRedisClient()
		localizer := pkgi18n.GetLocalizer()
		userSvc := userservice.NewUserService(db, redis, logger, tracer, localizer)
		
		// 创建模块
		module := NewModule(db, redis, logger, tracer, localizer, userSvc)
		
		// 初始化模块
		if err := module.Init(); err != nil {
			logger.Error("msg", "{{.ModuleName}}模块初始化失败", "error", err.Error())
			return
		}
		
		// 注册路由
		apiGroup := r.Group("")
		module.RegisterRoutes(apiGroup)
	})
	
	// 同时注册模块工厂
	registry.RegisterModuleFactory("{{.ModuleName}}", func(db *gorm.DB, logger logging.Logger, tracer opentracing.Tracer) (registry.APIModule, error) {
		// 创建所需的依赖
		redis := database.GetRedisClient()
		localizer := pkgi18n.GetLocalizer()
		userSvc := userservice.NewUserService(db, redis, logger, tracer, localizer)
		
		// 创建并返回模块实例
		module := NewModule(db, redis, logger, tracer, localizer, userSvc)
		return module, nil
	})
}
`

	// 准备模板数据
	data := struct {
		ModuleName string
	}{
		ModuleName: moduleName,
	}

	// 解析模板
	t, err := template.New("module_registration").Parse(tpl)
	if err != nil {
		return fmt.Errorf("解析模板失败: %w", err)
	}

	// 生成文件路径
	outputPath := filepath.Join(modulePath, "registration_gen.go")

	// 创建输出文件
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("创建文件失败: %w", err)
	}
	defer f.Close()

	// 执行模板
	if err := t.Execute(f, data); err != nil {
		return fmt.Errorf("执行模板失败: %w", err)
	}

	return nil
}
